# Generated by Django 4.0.2 on 2022-06-28 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('departure_city', models.CharField(max_length=255)),
                ('departure_time', models.DateTimeField()),
                ('arrival_city', models.CharField(max_length=255)),
                ('arrival_time', models.DateTimeField()),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
