# Generated by Django 4.0.5 on 2022-07-07 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='number',
            new_name='ticket_number',
        ),
    ]
